// Generates src/schemas.generated.ts from the canonical schemas/*.json.
// The published package embeds the schemas as JS objects so consumers can import
// them (and register them with their own validator) without reading files at
// runtime. Run via `npm run gen:schemas` (part of `npm run build`).
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const schemasDir = join(root, "schemas");
const outFile = join(root, "src", "schemas.generated.ts");

const files = readdirSync(schemasDir)
  .filter((f) => f.endsWith(".json"))
  .sort();

const entries = [];
for (const file of files) {
  const schema = JSON.parse(readFileSync(join(schemasDir, file), "utf8"));
  if (typeof schema.$id !== "string") {
    console.error(`✗ ${file} has no string $id; cannot key it.`);
    process.exit(1);
  }
  entries.push([schema.$id, schema]);
}

const body = entries
  .map(([id, schema]) => `  ${JSON.stringify(id)}: ${JSON.stringify(schema, null, 2).replace(/\n/g, "\n  ")},`)
  .join("\n");

const out = `// AUTO-GENERATED by scripts/gen-schemas.mjs from schemas/*.json. Do not edit.
// Run \`npm run gen:schemas\` to regenerate.

/** A JSON Schema document (2020-12 dialect), as a plain object. */
export type JSONSchema = Record<string, unknown>;

/** Every canonical AgentCompose schema, keyed by its \`$id\`. */
export const schemas: Record<string, JSONSchema> = {
${body}
};
`;

writeFileSync(outFile, out);
console.log(`Wrote ${outFile} (${entries.length} schemas).`);
